# Generated by Django 4.2.4 on 2023-10-12 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0005_user_addres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addres',
            new_name='address',
        ),
    ]
